<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Conversor_de_Arquivos\Conversor_de_Arquivos.csproj" />
    <ProjectReference Include="..\Modulo_Seguranca\Modulo_Seguranca.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Vigiagua_Logo.png" />
    <Resource Include="Assets\Vigiar_Logo.png" />
    <Resource Include="Assets\Vigidesastres_Logo.png" />
  </ItemGroup>    

</Project>